version: '3'
services:
  web:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./datapopulation_script:/var/www
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - db

  php:
    build:
      context: .
    volumes:
      - ./datapopulation_script:/var/www

  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: yvan2021
      MYSQL_DATABASE: e-commerce
      MYSQL_USER: root
      MYSQL_PASSWORD: yvan2021
